### ISSUE TITLE
Blacklist "a href"?

### ISSUE THREAD

**Issue by The-Compiler** [jwilk/anorack#1]
Yay for you continuing to improve the world by writing spellcheckers useful for source code! :+1: 

Unfortunately anorack is quite noisy when running it over `.html` files, due to `<a href="...">` constructs - example:

```
foo.html:19: a href -> an href /'eItSr'Ef/
```

Not sure what you think about specificially blacklisting cases, but I think it'd be worth it here.

**Comment by jwilk** [comment]
Thanks for the bug report.
I appreciate that `<a href=…>` is a great source of false positives.
I'm not sure what to do about it, though.
It's probably not as simple as blacklisting `a href`, because that could be [an actual misspelling](https://codesearch.debian.net/search?q=%28%3Fi%29%5Csa%5Cs%2Bhref%5Cs%2Battribute%5Cb).
And then, anorack is not aware of any kind of markup, so you should probably pre-process HTML anyway. Otherwise you risk it won't find thing like `an <em>user</em>`.

**Comment by The-Compiler** [comment]
Hmm, that's true. I've had some other common false positives (like `a http://example.com[thing]` in asciidoc), so probably pre-processing is indeed the way to go.
