### ISSUE TITLE
SHA needs an override

### ISSUE THREAD

**Issue by tbm** [jwilk/anorack#4]
>  an SHA -> a SHA /S'A:/

It's usually pronounced "es h a".

But I'm not sure. I think S.H.A. is most common but I think some people might say "sha".

**Comment by jwilk** [comment]
Hmm, I don't think I've ever heard it pronounced as "S.H.A."
To be sure, I've just checked a few random YouTube videos, and indeed they all say "shah":

* https://www.youtube.com/watch?v=DMtFhACPnTY
* https://www.youtube.com/watch?v=NbHL0SYlrSQ
* https://www.youtube.com/watch?v=kmHojGMUn0Q

**Comment by tbm** [comment]
Hmm, interesting. When I found this issue I googled and I found this post: https://crypto.stackexchange.com/questions/40150/how-are-the-names-of-cryptographic-algorithms-like-rsa-aes-sha-256-curve2551

But I don't really know. Maybe ask weasel on IRC :)  I'll trust whatever he says.

**Comment by jwilk** [comment]
> https://crypto.stackexchange.com/questions/40150/how-are-the-names-of-cryptographic-algorithms-like-rsa-aes-sha-256-curve2551

So the rationale for saying S.H.A. is that is to "make sure that your listeners understand you", presumably because they don't see text and are unfamiliar with the name.
But "an S.H.A." sounds very much like "N.S.H.A.", so I don't think it's an improvement over "a shah".

> Maybe ask weasel on IRC :)  I'll trust whatever he says.

He also pronounces it "shah".

**Comment by tbm** [comment]
Feel free to close then.
